version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
