// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].


== Unreleased

=== Changed

  - Additional arguments for `api.include` and `api.insert` are passed as attributes of the
    `include` directive.

=== Fixed

  - Matching elements in the same namespace are now preferred over elements in a different
    namespace. Only if all matches are in a parent namespace, the match will be ambiguous.


== 0.5.3 (16 May 2020)

=== Added

  - Allow filtering what members, enum values, inner classes, and exceptions get included when
      using api.insert().
  - Show progress bars for long running tasks.
  - Support for documenting python code with the help of doxypypy.
  - Specify a required version of AsciiDoxy in the adoc files.

=== Changed

  - Default log level decreased to warnings.


== 0.5.2 (24 Apr 2020)

=== Added

  - Support for free functions in C++


== 0.5.1 (22 Apr 2020)

=== Added

  - Added option multi\_page\_link to include() method, so an included adoc file is generated but
    not linked to in multi-page mode.


== 0.5.0 (21 Apr 2020)

=== Added

  - When api.insert or api.link is ambiguous, all matching candidates are shown.

=== Changed

  - Links that are part of an inserted element are also considered when looking for dangling links.

=== Fixed

  - Report full error information when collection fails.


== 0.4.3 (2 Apr 2020)

=== Fixed

* Nested enums are no longer ignored in Java.
* Fix enum template for Java. Descriptions are now complete and in the right column.


== 0.4.2 (30 Mar 2020)

=== Fixed

* Ignore friend declarations for C{plus}{plus}.
* Improve handling of Java generics.
* Improve type handling for Objective C.


== 0.4.1 (27 Mar 2020)

=== Added

* Disambiguate function overloads (and other callables) based on the types of the parameters.

=== Changed

* Search by name with an originating namespace now also finds partial namespace overlaps.
* Correctly take the originating namespace into account when resolving type references.

== 0.4.0 (19 Mar 2020)

=== Added

* Unknown command line options are now forwarded to AsciiDoctor.
* New collect module. Uses a package specification file to get Doxygen XML files and other include
  files from both remote (HTTP) locations and the local file system.
* Support for generating PDF files.

=== Changed

* Option `-a linkcss` is no longer provided to AsciiDoctor by default. You need to add it to the
  command line invocation of AsciiDoxy if needed.
* Command line parameters are updated to use the collect module instead of Artifactory.
* AsciiDoxy is now licensed under the Apache 2.0 license.
* Code style has been updated to match PEP-008, enforced by yapf.
* Docstrings have been updated to match Google style.
* All TomTom proprietary material has been removed. It is replaced by material under the Apache 2.0
  license.


== 0.3.4 (4 Mar 2020)

=== Added

* Support for enums in Java


== 0.3.3 (10 Feb 2020)

=== Added

* Support for downloading and extracting of multiple archive files per package

=== Changed

* Archives are downloaded to `download` directory
* The documentation is now built from an intermediate directory


== 0.3.2 (26 Feb 2020)

=== Fixed

* Prevent infinite loop on unrecognized function pointer type.


== 0.3.1 (20 Feb 2020)

=== Added

* Support for nested classes in Java and C++


== 0.3.0 (5 Feb 2020)

=== Added

* Argument `--multi-page` to generate separate page for each document included by `api.include()`
  call


== 0.2.2 (3 Feb 2020)

=== Added

* Support for Java interfaces.


== 0.2.1 (15 Jan 2020)

=== Added

* Argument `--force-language` to force the language used for reading Doxygen XML files. This is
  currently required to properly interpret Objective C header files.
* Support for Objective-C typedefs and blocks.


=== Changed

* Try to use the detailed description if there is no brief description.


=== Fixed

* Debug output is now valid, indented, JSON.
* Objective C types with a space are now correctly detected.
* Type resolving is not limited to just classes.
* Do not prepend header file name to Objective C types that are members of files only.
* Remove spurious spaces in method argument list when the argument has no name.


== 0.2.0 (23 Dec 2019)

=== Changed

* Short names are now default, use `full_name` to get the fully qualified name again.
* Parameters for `link`, `insert`, `link_*`, and `insert_*` have changed. The language and kind are
  no longer mandatory. They will be deduced if there is only one element with the specified name.
  An error is raised if there are multiple matches. Only `name` can be passed as positional
  argument now.

=== Fixed

* Remove surrounding whitespace for types and parameters. This caused incorrect rendering of
  monospace text.
* C{plus}{plus}: Include enclosed structs.

=== Removed

* The `short_name` argument for linking to documentation. This is now the default.


== 0.1.4 (12 Dec 2019)

=== Added

* Support inheritance in template files.
* Support for C++ interfaces (Doxygen concept).


== 0.1.3 (14 Nov 2019)

=== Added

* Show required include file for C++ and Objective C types.

=== Changed

* Static methods are separated from normal methods for Java.
* Class methods are separated from instance methods for Objective C.

=== Fixed

* Indentation of Objective C methods was off when the return type contained a link.
* Variables were missing from the overview of C++ structs.
* Decode templates and input document using UTF-8.
* Ignore Objective C methods marked NS_UNAVAILABLE.


== 0.1.2 (04 Nov 2019)

=== Added

* Support for C++ structs.
* Overview table for compound members.
* Include make in the Docker image.

=== Changed

* Show enclosed typedefs in C++ classes and structs.
* Improved formatting.
* Clean up extra whitespace.


== 0.1.1 (04 Nov 2019)

=== Fixed

* Fix publishing Docker image on CI.


== 0.1.0 (22 Oct 2019)

* First internal release.

