// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= A basic AsciiDoc file
${include("../_header.adoc", always_embed=True, leveloffset=None)}

In essence AsciiDoxy is a preprocessor for AsciiDoc files. It looks for special directives in these
files and replaces them with valid AsciiDoc. Then it runs AsciiDoctor to generate HTML or PDF from
the AsciiDoc files. To write documentation with AsciiDoxy, you need to know how to write an AsciiDoc
file.

Let's start with writing a basic AsciiDoc file, and using AsciiDoxy to generate an HTML file.

:sectnums:
== The AsciiDoc file

Use your favorite text editor to create a new file named `my-first-document.adoc`. Enter the
following text:

[source]
----
= My first document

This is my first document written for AsciiDoxy.

== The story begins

Today I am so *bold* to write _cursively_ in "`AsciiDoc`".
----

To learn more about the formatting supported by AsciiDoctor, see:

* https://asciidoctor.org/docs/user-manual[The AsciiDoctor User Manual.]
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[The AsciiDoc Syntax Quick
  Reference.]

== Running AsciiDoxy

Use AsciiDoxy to generate a beautiful HTML document:

[source,bash]
----
asciidoxy my-first-document.adoc
----

If AsciiDoxy is installed correctly and there are no errors in the file, you should see the
AsciiDoxy logo and a couple of progress bars. After the last progress bar hits 100%, AsciiDoxy will
exit.

Now there should be a new `build` directory in the directory where you ran the command. This `build`
directory contains temporary files generated by AsciiDoxy, and an `output` directory. The
`build/output` directory contains the HTML output: `my-first-document.html`. If you open it in your
browser, it should look like this:

.Rendered document
====
[discrete]
= My first document

This is my first document written for AsciiDoxy.

[discrete]
== The story begins

Today I am so *bold* to write _cursively_ in "`AsciiDoc`".
====

=== Changing the location of the output

You can specify a different directory to store the output in using command-line option
`--destination-dir` (or `-D`):

[source,bash]
----
asciidoxy my-first-document.adoc --destination-dir my-output
----

It is also possible to store the temporary build files in a different location by using command-line
option `--build-dir`:

[source,bash]
----
asciidoxy my-first-document.adoc --destination-dir my-output --build-dir /tmp/asciidoxy
----

NOTE: If you do not explicitly specify a destination directory, the output will move together with
the temporary build files.

All available command-line options can be found in
${cross_document_ref("../reference/command-line-options.adoc",
                     link_text="the reference documentation for command-line options")}.
