// Copyright (C) 2019, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Custom templates
${include("../_header.adoc", always_embed=True, leveloffset=None)}

WARNING: This feature is *experimental*. The API used by the templates is currently not stable and 
may change without warning in any update of AsciiDoxy.

AsciiDoxy comes with builtin templates to generate API reference for the programming languages it 
supports. It is possible to provide your own set of templates to customize or extend the output 
generated by AsciiDoxy.

:sectnums:
== Custom template directory

Custom templates need to be provided to AsciiDoxy using the `--template-dir` command line argument. 
The argument must point to an existing directory with a predefined structure.

[source,bash]
----
asciidoxy --template-dir src/templates my-document.adoc
----

Templates are stored in a subdirectory for the language they apply to. The filename is the name of 
the kind of element with the extension `.mako`.

For example a template directory where the `class` template for `c++` and `java` are overridden 
should look like this:

----
templates
├── cpp
│   └── class.mako
└── java
    └── class.mako
----

== Replacing builtin templates

The custom template directory can be used to replace the builtin templates. When a template 
directory is provided, AsciiDoxy will always first check whether a custom version of the template 
is present. If it its, it will prefer the custom version, otherwise it will fall back to the 
builtin templates.

The builtin templates can be found in the source code of AsciiDoxy in 
`asciidoxy/generator/templates`. You can copy the templates to customize into your custom templates 
directory as a starting point.

== Using custom templates for specific cases

Alternatively, custom templates can be used explicitly in `insert` commands. Then the custom 
template is only used for that specific `insert` command. To use this, make sure the custom 
template has a name that is not used yet for a builtin template:

----
templates
└── java
    └── mycustomclass.mako
----

In your AsciiDoc documents you can explicitly use the template by providing the `template` argument 
to the `insert` command:

[source,python]
----
${"""
${insert("MyNamespace::MyClass", template="mycustomclass")}
"""}
----
