// Copyright (C) 2019-2021, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Objective C
${include("../../_header.adoc", always_embed=True, leveloffset=None)}

This is an example demonstrating documentation for an Objective C project. The used source code
files come from the https://github.com/AFNetworking/AFNetworking[AFNetworking] project.

NOTE: This is not meant to be complete documentation. Some links in the documentation may not work
due to missing documentation.

.Doxygen configuration
[source]
----
include::Doxyfile[]
----

.AsciiDoxy directives
[source,python]
----
${"""
${language("objc")}
${insert("AFHTTPSessionManager")}
${insert("AFHTTPRequestSerializer")}
${insert("AFURLRequestSerialization")}
${insert("AFMultipartFormData")}
"""}
----

${language("objc")}
${insert("AFHTTPSessionManager")}
${insert("AFHTTPRequestSerializer")}
${insert("AFURLRequestSerialization")}
${insert("AFMultipartFormData")}
