// Copyright (C) 2019, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Kotlin transcoded from Java
${include("../../_header.adoc", always_embed=True, leveloffset=None)}

This is an example demonstrating documentation for a Java project transcoded to Kotlin. The used
source code files come from the https://gitbox.apache.org/repos/asf?p=commons-io.git[Apache Commons
IO] project.

NOTE: This is not meant to be complete documentation. Some links in the documentation may not work
due to missing documentation.

.Doxygen configuration
[source]
----
include::Doxyfile[]
----

.AsciiDoxy directives
[source,python]
----
${"""
${language("kotlin", source="java")}
${insert("org.apache.commons.io.FileCleaningTracker")}
${insert("org.apache.commons.io.FileDeleteStrategy")}
"""}
----

${language("kotlin", source="java")}
${insert("org.apache.commons.io.FileCleaningTracker")}
${insert("org.apache.commons.io.FileDeleteStrategy")}

