// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Kotlin transcoded from Java
:notitle:
:icons: font
:doctype: book
:source-highlighter: highlightjs
:toc: right
:toc-title: On this page
${api.multipage_toc()}

----
    ___              _ _ ____
   /   |  __________(_|_) __ \____  _  ____  __
  / /| | / ___/ ___/ / / / / / __ \| |/_/ / / /
 / ___ |(__  ) /__/ / / /_/ / /_/ />  </ /_/ /
/_/  |_/____/\___/_/_/_____/\____/_/|_|\__, /
                                      /____/
----

[ ${api.cross_document_ref("../../index.adoc", "", "Home")} |
${api.cross_document_ref("../../about.adoc", "", "What is AsciiDoxy?")} |
${api.cross_document_ref("../../usage.adoc", "", "Usage")} |
${api.cross_document_ref("../../examples.adoc", "", "Examples")} |
${api.cross_document_ref("../../contributing.adoc", "", "Contributing")} |
${api.cross_document_ref("../../changelog.adoc", "", "Changelog")} |
https://github.com/tomtom-international/asciidoxy[GitHub] ]

= {doctitle}

This is an example demonstrating documentation for a Java project transcoded to Kotlin. The used
source code files come from the https://gitbox.apache.org/repos/asf?p=commons-io.git[Apache Commons
IO] project.

NOTE: This is not meant to be complete documentation. Some links in the documentation may not work
due to missing documentation.

.Doxygen configuration
[source]
----
include::Doxyfile[]
----

.AsciiDoxy directives
[source,python]
----
${"""
${api.language("kotlin", source="java")}
${api.insert("org.apache.commons.io.FileCleaningTracker")}
${api.insert("org.apache.commons.io.FileDeleteStrategy")}
"""}
----

${api.language("kotlin", source="java")}
${api.insert("org.apache.commons.io.FileCleaningTracker")}
${api.insert("org.apache.commons.io.FileDeleteStrategy")}

