// Copyright (C) 2019, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
:notitle:
:icons: font
:doctype: book
:source-highlighter: highlightjs
:toc: right
:toc-title: On this page
${multipage_toc()}

----
    ___              _ _ ____
   /   |  __________(_|_) __ \____  _  ____  __
  / /| | / ___/ ___/ / / / / / __ \| |/_/ / / /
 / ___ |(__  ) /__/ / / /_/ / /_/ />  </ /_/ /
/_/  |_/____/\___/_/_/_____/\____/_/|_|\__, /
                                      /____/
----

[ ${cross_document_ref("index.adoc", link_text="Home")} |
${cross_document_ref("about.adoc", link_text="What is AsciiDoxy?")} |
${cross_document_ref("getting-started.adoc", link_text="Getting started")} |
${cross_document_ref("reference.adoc", link_text="Reference documentation")} |
${cross_document_ref("examples.adoc", link_text="Examples")} |
${cross_document_ref("contributing.adoc", link_text="Contributing")} |
${cross_document_ref("changelog.adoc", link_text="Changelog")} |
https://github.com/tomtom-international/asciidoxy[GitHub] ]

= {doctitle}

