// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= AsciiDoxy
:notitle:
:toc: left
:toc-title: AsciiDoxy
:icons: font
:doctype: book
:source-highlighter: highlightjs

----
    ___              _ _ ____
   /   |  __________(_|_) __ \____  _  ____  __
  / /| | / ___/ ___/ / / / / / __ \| |/_/ / / /
 / ___ |(__  ) /__/ / / /_/ / /_/ />  </ /_/ /
/_/  |_/____/\___/_/_/_____/\____/_/|_|\__, /
                                      /____/
----

[ ${api.cross_document_ref("index.adoc", "", "Home")} |
${api.cross_document_ref("about.adoc", "", "What is AsciiDoxy?")} |
${api.cross_document_ref("usage.adoc", "", "Usage")} |
${api.cross_document_ref("examples.adoc", "", "Examples")} |
${api.cross_document_ref("contributing.adoc", "", "Contributing")} |
${api.cross_document_ref("changelog.adoc", "", "Changelog")} |
https://github.com/tomtom-international/asciidoxy[GitHub] ]

= Contributing

AsciiDoxy is developed in python 3.6. For development it is recommended to set up a virtual
environment with all dependencies. Use the following commands to quickly set up the entire
environment:

[source,bash]
----
make virtualenv
----

Then enable the virtual environment to be able to run tests:

[source,bash]
----
. .venv/bin/activate
----

The make file defines several other helpful commands:

`make test`:: Run unit tests using the current python version.
`make lint`:: Check code style.
`make type-check`:: Static analysis using type hints.
`make test-all`:: Run all checks and tests on all available and supported python versions.
`make dist`:: Create distribution packages in `dist/`.
`make release`:: Upload packages created with `make dist` to PyPI.

Before creating a PR, you should run `make test-all` to run all tests, the linter and the type
checker. Packaging and specified requirements are verified as well by installing into a clean
virtual environment. Tests will be run on all available, and supported, python versions.

== Architecture overview

Components:

`collect`:: Collect API reference information from local and remote files.
`doxygenparser`:: Reads the Doxygen XML files and creates an internal representation that can be
converted to AsciiDoc.
`model`:: Internal representation of API reference elements.
`generator`:: Enriches an AsciiDoc file with API reference information.
`templates`:: Templates used to generate API reference information.
`cli`:: The command line interface.

== Adding programming language support

`DoxygenXmlParser` (in `doxygenparser.parser`) is the main entry point for loading the API
reference from Doxygen XML files. It uses an instance of `Language` to parse XML files with
language specific transformations. Too add support for an extra language:

- Add a subclass of `Language`.
- Register it in the constructor of `DoxygenXmlParser`.
- If needed, add aliases in `safe_language_tag`.

== Adding methods for use in AsciiDoc files

The entry point for enriching an AsciiDoc file is `process_adoc()`. It treats the AsciiDoc input
file as a Mako template. Any https://docs.makotemplates.org/en/latest/syntax.html[Mako syntax] can
be used in the AsciiDoc file. API enrichment methods are provided by passing an instance of `Api` to
the Mako processor. It is exposed in the document as `api`. Add methods to `Api` to provide more
functionality to document writers.

== Supporting more kinds of API reference elements

API reference fragments are also generated from Mako templates. These templates are in
`asciidoxy/templates` and are organised in separate directories per programming language. To add
support for a specific API reference element, add a Mako template with the name of the element in
the directory for the corresponding programming language. It will automatically be picked up when an
insert method is called. The special method `getattr` is used to provide the `insert_<kind>` and
`link_<kind>` methods.

== Coding style

For coding style we use https://www.python.org/dev/peps/pep-0008/[PEP8], enforced by
https://github.com/google/yapf[yapf]. For docstrings we follow
http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings[Google Style].

== Test data

Where possible, Doxygen XML files for testing are generated from custom source code. This allows
checking compatibility with different Doxygen versions. Inside the `tests` directory there are
multiple directories for test data:

- `adoc`: AsciiDoc input files for testing. Usually pairs of `<NAME>.input.adoc` and
  `<NAME>.expected.adoc`. The expected file contains what AsciiDoxy should output when processing
  the input file.
- `data`: Handcrafted test data.
- `source_code`: The source code from which Doxygen XML test data is generated.
- `xml`: Doxygen XML test data generated from the source code.

The Doxygen XML data can be regenerated by running `tests/source_code/generate_xml.py`, and
providing the path to the version of Doxygen to use.

NOTE: A separate directory is created for each version of Doxygen. The tests will run on each
directory.

The expectations for the tests in `test_templates.py` can be easily regenerated when templates have
been changed. Run `pytest --update-expected-results` to overwrite the current expectations with the
new output. Make sure to check the diff to see if there are no unexpected side effects!
