// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Examples
:notitle:
:icons: font
:doctype: book
:source-highlighter: highlightjs
:toc: right
:toc-title: On this page
${api.multipage_toc()}

----
    ___              _ _ ____
   /   |  __________(_|_) __ \____  _  ____  __
  / /| | / ___/ ___/ / / / / / __ \| |/_/ / / /
 / ___ |(__  ) /__/ / / /_/ / /_/ />  </ /_/ /
/_/  |_/____/\___/_/_/_____/\____/_/|_|\__, /
                                      /____/
----

[ ${api.cross_document_ref("index.adoc", "", "Home")} |
${api.cross_document_ref("about.adoc", "", "What is AsciiDoxy?")} |
${api.cross_document_ref("usage.adoc", "", "Usage")} |
${api.cross_document_ref("examples.adoc", "", "Examples")} |
${api.cross_document_ref("contributing.adoc", "", "Contributing")} |
${api.cross_document_ref("changelog.adoc", "", "Changelog")} |
https://github.com/tomtom-international/asciidoxy[GitHub] ]

= {doctitle}

These are some examples of AsciiDoxy in action. They demonstrate documentation for source code used
to test AsciiDoxy. The first example is the website you are looking at. It is completely generated
using AsciiDoxy.

== C++ class

Insert a basic C++ class:

[source,python]
----
${"""
${api.insert("asciidoxy::geometry::Coordinate", leveloffset="+3")}
"""}
----

.Source code
[%collapsible]
====
[source,cpp]
----
include::./source_code/cpp/default/coordinate.hpp[]
----
====

=== Output

${api.insert("asciidoxy::geometry::Coordinate", leveloffset="+3")}

== Java class

Insert a basic Java class:

[source,python]
----
${"""
${api.insert("com.asciidoxy.geometry.Coordinate", leveloffset="+3")}
"""}
----

.Source code
[%collapsible]
====
[source,java]
----
include::./source_code/java/default/Coordinate.java[]
----
====

=== Output

${api.insert("com.asciidoxy.geometry.Coordinate", leveloffset="+3")}

== Objective C interface

Insert a basic Objective C interface:

[source,python]
----
${"""
${api.insert("ADCoordinate", leveloffset="+3")}
"""}
----

.Source code
[%collapsible]
====
[source,objectivec]
----
include::./source_code/objc/default/ADCoordinate.h[]
----
====

=== Output

${api.insert("ADCoordinate", leveloffset="+3", lang="objc")}
${api.insert("ADTrafficEvent", leveloffset="+3", lang="objc")}

== Python class

Insert a python class:

[source,python]
----
${"""
${api.insert("asciidoxy.geometry.Coordinate", leveloffset="+3")}
"""}
----

.Source code
[%collapsible]
====
[source,python]
----
include::./source_code/python/default/asciidoxy/geometry.py[]
----
====

=== Output

${api.insert("asciidoxy.geometry.Coordinate", leveloffset="+3")}

== Swift transcoding from Objective C

Insert a basic Objective C interface transcoded to Swift:

[source,python]
----
${"""
${language("swift", source="objc")}
${api.insert("ADCoordinate", leveloffset="+3")}
"""}
----

.Source code
[%collapsible]
====
[source,objectivec]
----
include::./source_code/objc/default/ADCoordinate.h[]
----
====

=== Output

${api.language("swift", source="objc")}
${api.insert("ADCoordinate", leveloffset="+3")}
${api.insert("ADTrafficEvent", leveloffset="+3")}
