// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Objective C
:notitle:
:icons: font
:doctype: book
:source-highlighter: highlightjs
:toc: right
:toc-title: On this page
${api.multipage_toc()}

----
    ___              _ _ ____
   /   |  __________(_|_) __ \____  _  ____  __
  / /| | / ___/ ___/ / / / / / __ \| |/_/ / / /
 / ___ |(__  ) /__/ / / /_/ / /_/ />  </ /_/ /
/_/  |_/____/\___/_/_/_____/\____/_/|_|\__, /
                                      /____/
----

[ ${api.cross_document_ref("index.adoc", "", "Home")} |
${api.cross_document_ref("about.adoc", "", "What is AsciiDoxy?")} |
${api.cross_document_ref("usage.adoc", "", "Usage")} |
${api.cross_document_ref("examples.adoc", "", "Examples")} |
${api.cross_document_ref("contributing.adoc", "", "Contributing")} |
${api.cross_document_ref("changelog.adoc", "", "Changelog")} |
https://github.com/tomtom-international/asciidoxy[GitHub] ]

= {doctitle}

This example shows documentation for an Objective C project. The documentation is generated using
the following AsciiDoxy directives:

[source,python]
----
${"""
${api.language("objc")}
${api.insert("ADCoordinate")}
${api.insert("ADTrafficEvent")}
"""}
----

.Source code for which the documentation is generated
[%collapsible]
====
[source,objectivec]
----
include::./source_code/objc/default/ADCoordinate.h[]
----
====

${api.language("objc")}
${api.insert("ADCoordinate")}
${api.insert("ADTrafficEvent")}

