// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Examples
:notitle:
:icons: font
:doctype: book
:source-highlighter: highlightjs
:toc: right
:toc-title: On this page
${api.multipage_toc()}

----
    ___              _ _ ____
   /   |  __________(_|_) __ \____  _  ____  __
  / /| | / ___/ ___/ / / / / / __ \| |/_/ / / /
 / ___ |(__  ) /__/ / / /_/ / /_/ />  </ /_/ /
/_/  |_/____/\___/_/_/_____/\____/_/|_|\__, /
                                      /____/
----

[ ${api.cross_document_ref("index.adoc", "", "Home")} |
${api.cross_document_ref("about.adoc", "", "What is AsciiDoxy?")} |
${api.cross_document_ref("usage.adoc", "", "Usage")} |
${api.cross_document_ref("examples.adoc", "", "Examples")} |
${api.cross_document_ref("contributing.adoc", "", "Contributing")} |
${api.cross_document_ref("changelog.adoc", "", "Changelog")} |
https://github.com/tomtom-international/asciidoxy[GitHub] ]

= {doctitle}

These are some examples of AsciiDoxy in action. They demonstrate documentation for source code used
to test AsciiDoxy. The first example is the website you are looking at. It is completely generated
using AsciiDoxy.

${api.include("examples/cpp/example-cpp.adoc", link_text="{Cpp}", link_prefix=". ")}
${api.include("examples/java/example-java.adoc", link_text="Java", link_prefix=". ")}
${api.include("examples/objc/example-objc.adoc", link_text="Objective C", link_prefix=". ")}
${api.include("examples/objc/example-swift-transcoded.adoc", link_text="Swift transcoded from Objective C", link_prefix=". ")}
${api.include("examples/python/example-python.adoc", link_text="Python", link_prefix=". ")}

