// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Getting started
${include("_header.adoc", always_embed=True, leveloffset=None)}

A step-by-step guide to get you started with AsciiDoxy.

. ${cross_document_ref("getting-started/installation.adoc", link_text="Installation")}: Install
  AsciiDoxy and everything required to run it.
. ${cross_document_ref("getting-started/basic-asciidoc-file.adoc",
                           link_text="A basic AsciiDoc file")}:
  Generating HTML out of a basic AsciiDoc file.
. ${cross_document_ref("getting-started/using-python.adoc",
                           link_text="Using python in AsciiDoc files")}:
  Using python code to generate parts of your documentation.
. ${cross_document_ref("getting-started/multipage.adoc",
                           link_text="Multipage documents")}:
  Splitting the HTML output into multiple pages with convenient navigation.
. ${cross_document_ref("getting-started/packages.adoc", link_text="Packages")}:
  Separating documentation in packages.
. ${cross_document_ref("getting-started/api-reference.adoc",
                           link_text="Including API reference")}:
  Add API reference documentation extracted from source code.

${include("getting-started/installation.adoc", multipage_link=False)}
${include("getting-started/basic-asciidoc-file.adoc", multipage_link=False)}
${include("getting-started/using-python.adoc", multipage_link=False)}
${include("getting-started/multipage.adoc", multipage_link=False)}
${include("getting-started/packages.adoc", multipage_link=False)}
${include("getting-started/api-reference.adoc", multipage_link=False)}
