// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Getting started
${api.include("_header.adoc", always_embed=True, leveloffset=None)}

A step by step guide to get you started with AsciiDoxy.

. ${api.cross_document_ref("getting-started/installation.adoc", link_text="Installation")}: Install
  AsciiDoxy and everything required to run it.
. ${api.cross_document_ref("getting-started/basic-asciidoc-file.adoc",
                           link_text="A basic AsciiDoc file")}:
  Generating HTML out of a basic AsciiDoc file.
. ${api.cross_document_ref("getting-started/using-python.adoc",
                           link_text="Using python in AsciiDoc files.")}:
  Using python code to generate parts of your documentation.
. Multipage documents.
. Separating documentation in packages.
. Including API reference.

${api.include("getting-started/installation.adoc", multipage_link=False)}
${api.include("getting-started/basic-asciidoc-file.adoc", multipage_link=False)}
${api.include("getting-started/using-python.adoc", multipage_link=False)}
