// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= AsciiDoxy
${api.include("_header.adoc", always_embed=True, leveloffset=None)}

image:https://img.shields.io/badge/License-Apache%202.0-green.svg[License, link=LICENSE]
image:https://img.shields.io/pypi/dm/asciidoxy[pip downloads, link=https://pypi.org/project/asciidoxy]
image:https://img.shields.io/pypi/pyversions/asciidoxy[PyPI - Python Version, link=https://pypi.org/project/asciidoxy]
image:https://img.shields.io/pypi/v/asciidoxy[PyPI, link=https://pypi.org/project/asciidoxy]

AsciiDoxy generates API documentation from https://doxygen.nl[Doxygen] XML output to AsciiDoc.
https://asciidoctor.org[AsciiDoctor] is then used to create HTML or PDF documentation that can be
published online.

Supported languages:

- C++
- Java
- Objective-C
- Python (using https://github.com/Feneric/doxypypy[doxypypy])
- Swift (transcoded from Objective-C only)
- Kotlin (transcoded from Java only)

Features:

- API documentation generation.
- Collecting API reference information from remote and local sources.
- Single and multipage HTML output.
- Single page PDF output.
- Transcoding: showing how to use elements written in one language in another compatible language.


== Credits

Inspiration for creating AsciiDoxy was found in this article by Sy Brand:
https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/

Before going public on GitHub, several people inside https://www.tomtom.com[TomTom] contributed to
the internal version of AsciiDoxy. Many thanks to:

- Andy Salter
- Arkadiusz Skalski
- Lukasz Glowcyk
- Nebojsa Mrmak
- Niels van der Schans
- Robert Gernert
- Tomasz Maj

The python package was created with https://github.com/audreyr/cookiecutter[Cookiecutter] and the
https://github.com/audreyr/cookiecutter-pypackage[audreyr/cookiecutter-pypackage] project template.

${api.include("about.adoc", multipage_link=False)}
${api.include("getting-started.adoc", multipage_link=False)}
${api.include("reference.adoc", multipage_link=False)}
${api.include("examples.adoc", multipage_link=False)}
${api.include("contributing.adoc", multipage_link=False)}
${api.include("changelog.adoc", multipage_link=False)}
