// Copyright (C) 2019, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= AsciiDoxy
${include("_header.adoc", always_embed=True, leveloffset=None)}

image:https://img.shields.io/badge/License-Apache%202.0-green.svg[License, link=LICENSE]
image:https://img.shields.io/pypi/dm/asciidoxy[pip downloads, link=https://pypi.org/project/asciidoxy]
image:https://img.shields.io/pypi/pyversions/asciidoxy[PyPI - Python Version, link=https://pypi.org/project/asciidoxy]
image:https://img.shields.io/pypi/v/asciidoxy[PyPI, link=https://pypi.org/project/asciidoxy]

AsciiDoxy let's you generate beautiful documentation using the combined power of AsciiDoc and 
Python. Write your documentation in https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc format]
and use https://python.org[Python code] and https://makotemplates.org[Mako Templates] to generate 
additional content. To top it all off, insert API documentation generated by 
https://doxygen.nl[Doxygen] to document your software.

For API documentation, the following languages are currently supported through Doxygen:

- C++
- Java
- Objective-C
- Python (using https://github.com/Feneric/doxypypy[doxypypy])
- Swift (transcoded from Objective-C only, native support expected in 0.9.x)
- Kotlin (transcoded from Java only, native support expected in 0.9.x)

Other features:

- Collect AsciiDoc files, images, API documentation and other resources from remote servers.
- Generate either a single HTML page or a multipage hierarchy.
- Transcoding: showing how to use elements written in one language in another compatible language.


== Get started now!

Want to try out AsciiDoxy together with all the tools it supports? Use our Docker image:

```bash
docker run --rm -it silvester747/asciidoxy:latest asciidoxy --help
```

All you need to get started writing beautiful documentation can be found in our
${cross_document_ref("getting-started.adoc", link_text="getting started guide")}.

== Credits

Inspiration for creating AsciiDoxy was found in this article by Sy Brand:
https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/

Before going public on GitHub, several people inside https://www.tomtom.com[TomTom] contributed to
the internal version of AsciiDoxy. Many thanks to:

- Andy Salter
- Arkadiusz Skalski
- Lukasz Glowcyk
- Nebojsa Mrmak
- Niels van der Schans
- Robert Gernert
- Tomasz Maj

The python package was created with https://github.com/audreyr/cookiecutter[Cookiecutter] and the
https://github.com/audreyr/cookiecutter-pypackage[audreyr/cookiecutter-pypackage] project template.

${include("about.adoc", multipage_link=False)}
${include("getting-started.adoc", multipage_link=False)}
${include("reference.adoc", multipage_link=False)}
${include("examples.adoc", multipage_link=False)}
${include("contributing.adoc", multipage_link=False)}
${include("changelog.adoc", multipage_link=False)}
