// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Manual
${api.include("_header.adoc", always_embed=True, leveloffset=None)}

${api.include("manual/requirements.adoc", link_text="Requirements", link_prefix=". ")}
${api.include("manual/command-line-options.adoc", link_text="Command-line options", link_prefix=". ")}
${api.include("manual/packages.adoc", link_text="Packages", link_prefix=". ")}
${api.include("manual/commands.adoc", link_text="Commands", link_prefix=". ")}
${api.include("manual/doxygen.adoc", link_text="Doxygen", link_prefix=". ")}

== TODO

${api.include("usage.adoc", link_text="Usage", link_prefix=". ")}
