// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Usage
${api.include("_header.adoc", always_embed=True, leveloffset=None)}

Instructions for how to install and use AsciiDoxy to create your own AsciiDoc API reference
documentation.

== Preparing API reference

AsciiDoxy uses XML output from Doxygen to generate API reference documentation. To include the API
reference documentation in AsciiDoc files you need to:

. Run Doxygen to extract the documentation from the source and store it in XML format.
. Specify where AsciiDoxy should look for the extracted documentation using a package specification
  file.

== Writing documentation
${api.namespace("asciidoxy.generator.asciidoc")}

AsciiDoxy works on documentation written in AsciiDoc. AsciiDoctor is used for the tranformation to
the output format. All https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc
Syntax] supported by AsciiDoctor can be used. For a detailed reference see the
https://asciidoctor.org/docs/user-manual[AsciiDoctor Manual]

To customize the documentation before it is processed by AsciiDoctor, AsciiDoxy allows using
https://docs.makotemplates.org/en/latest/syntax.html[Mako syntax] in the AsciiDoc files.  Mako
syntax looks like `${"${...}"}` where `...` can contain any valid python code. This python code is
executed when the file is processed by AsciiDoxy.

A special object `${api.link("Api", text="api")}` is  added to the Mako context when the document
is processed. The object can be used in places where Mako executes python code, usualy the
`${"${...}"}` blocks. It provides methods to insert API reference documentation and link to its
elements.

