// Copyright (C) 2019-2020, TomTom (http://tomtom.com).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Usage
:toc:

TODO

== Installation

The preferred way to install AsciiDoxy is to use pip:

[source,bash]
----
pip3 install asciidoxy
----

Alternatively you can directly install the development version by cloning the source and running:

[source,bash]
----
make install
----

== Invocation

The minimal invocation takes an input AsciiDoc file and a package specification file. It creates a
single page HTML document.

[source,bash]
----
asciidoxy --spec-file package_spec.toml input_file.adoc
----

To see all command line options, run:

[source,bash]
----
asciidoxy --help
----

----
<%
import subprocess
%>
${subprocess.run("asciidoxy --help", capture_output=True, shell=True, encoding="utf-8").stdout}
----

== Preparing API reference

AsciiDoxy uses XML output from Doxygen to generate API reference documentation. To include the API
reference documentation in AsciiDoc files you need to:

. Run Doxygen to extract the documentation from the source and store it in XML format.
. Specify where AsciiDoxy should look for the extracted documentation using a package specification
  file.


=== Running Doxygen

For extracting documentation from source code, AsciiDoxy relies on Doxygen. You are expected to run
Doxygen on your source code, and then provide the path to the generated XML files to AsciiDoxy. It
is recommended to set at least the following non-default settings in your Doxyfile when generating
the XML.

==== C++

----
GENERATE_XML           = YES
----

==== Java

----
GENERATE_XML           = YES
JAVADOC_AUTOBRIEF      = YES
OPTIMIZE_OUTPUT_JAVA   = YES
----

==== Objective C

----
GENERATE_XML           = YES
EXTENSION_MAPPING      = h=objective-c
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
PREDEFINED             = NS_ASSUME_NONNULL_BEGIN= NS_UNAVAILABLE=
----

==== Python

To fully support python docstrings formats like the Google Python Style Guide it is recommended to
use https://github.com/Feneric/doxypypy[doxypypy] as a filter for Doxygen.

----
GENERATE_XML           = YES
FILTER_PATTERNS        = *.py="doxypypy -a -c"
----

Support for type hints in Doxygen is still limited: https://github.com/doxygen/doxygen/issues/7320.

=== Package specification files

AsciiDoxy needs to know where to find the XML files containing the API reference documentation. It
supports loading these files from a local directory or from a remote HTTP server. Package
specification files describe where to collect the XML files.

A single location containing the XML files is called a package. The idea is that each package
corresponds to an isolated component that can be included as a separate package. Documentation for
separate packages can refer to each other when used in combination.

Packages can contain additional resources like images, example source code, and AsciiDoc files.
These resources can be referred to from the input AsciiDoc files.

Package specification files use https://github.com/toml-lang/toml[TOML] format. They can contain the
following sections:

`packages`:: Specification of packages to include.
`sources`:: Templates for similar packages.

==== Packages

The `packages` section is the only mandatory section. It contains a separate subsection for each
package to include. The name of the subsection is the name of the package:

[source,toml]
----
[packages]

[packages.package1]
# Specification of `package1`

[packages.package2]
# Specification of `package2`
----

A package has a specific type and based on the type different key/value pairs are required. For all
types of packages the following key/value pairs are required:

`type`:: The type of the package.
`xml_subdir`:: Subdirectory in the root of the package in which all Doxygen XML files are stored.
`include_subdir`:: Subdirectory in the root of the package in which all other include files are
stored.

Packages of type `local` refer to a local directory. They require the following additional key/value
pairs:

`package_dir`:: Absolute or relative path to the directory containing the package.

Example:

[source,toml]
----
[packages.local_package]
type = "local"
xml_subdir = "xml"
include_subdir = "adoc"
package_dir = "/path/to/my/package/"
----

Packages of type `http` are downloaded from a remote location. They can consist of multiple files,
all of which need to be (compressed) tarballs. Each file can contain XML files, include files, or
both.

The following additional key/value pairs are required:

`url_template`:: Template for constructing the URL to download the package file from.
`file_names`:: List of file names making up the package.

The following additional key/value pairs are optional:

`version`:: Version number of the package.

The `url_template` can contain the following placeholders, that are replaced when creating the URL
to download each package file:

`{name}`:: Replaced with the name of the package.
`{version}`:: Replaced with the version of the package.
`{file_name}`:: Replaced with the file name.

Example:

[source,toml]
----
[packages]

[packages.package1]
type = "http"
url_template = "https://example.com/{name}/{version}/{file_name}"
xml_subdir = "xml"
include_subdir = "adoc"
version = "12.3.4"
----

If no `version` is specified for the package, the version is retrieved from a version file. The
version file is a comma separated values file containing pairs of package names and corresponding
versions. It can contain any number of fields, but it is required to have a header containing the
names `Component name` and `Version` for the columns containing these.

Example:

----
Component name, Version
package1,3.0.0
package2,4.5.1
----

==== Sources

The `sources` section allows specifying templates for packages. Each template can specify a common
"source" of packages. With a source, settings that are duplicated for many packages can be specified
only once.

A source section can contain every key/value pair that is allowed for a package. Packages can
specify the source they are based on by using the `source` key/value pair.

When a source is used, the key/value pairs of the source and the pacakge are merged. Values for keys
that are present in both the package and the source will be taken from the package. So the package
values override source values.

Example:

[source,toml]
----
[sources]

[sources.remote_server]
type = "http"
url_template = "https://example.com/{name}/{version}/{file_name}"
xml_subdir = "xml"
include_subdir = "adoc"

[packages]

[packages.package1]
source = "remote_server"
version = "12.3.4"
----

== Writing documentation


