name: Verify changes on branches
# Runs on all branches other than master/main. Running on push should be enough for PRs.
# Only when changes are pushed to develop branches, a development Docker image is pushed

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    name: Test python package
    uses: ./.github/workflows/python-test.yml

  docker:
    name: Create and test Docker images
    uses: ./.github/workflows/docker.yml
    needs: test
    with:
      release: false
      push: ${{ startswith(github.ref, 'refs/heads/develop') }}
    secrets: inherit

  check:
    name: All passed
    needs: [test, docker]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All OK
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Something failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
